/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author Alexander
 */
public class VistaPassenger extends javax.swing.JFrame {

    /**
     * Creates new form VistaPassenger
     */
    public VistaPassenger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbConnectionState = new javax.swing.JLabel();
        lbRequestState = new javax.swing.JLabel();
        lbDriversAvailable = new javax.swing.JLabel();
        btnCancelRequest = new javax.swing.JButton();
        btnRequestDriver = new javax.swing.JButton();
        btnConnect = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbConnectionState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbConnectionState.setText("Estado:");

        lbRequestState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbRequestState.setText("Estado de solicitud: ");

        lbDriversAvailable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbDriversAvailable.setText("Moviles disponibles: ");

        btnCancelRequest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelRequest.setText("Cancelar");
        btnCancelRequest.setEnabled(false);

        btnRequestDriver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRequestDriver.setText("Solicitar Taxi");
        btnRequestDriver.setEnabled(false);

        btnConnect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConnect.setText("Conectar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDriversAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRequestState, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbConnectionState, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConnect)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRequestDriver)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelRequest)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbConnectionState, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDriversAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRequestState, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConnect)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelRequest)
                    .addComponent(btnRequestDriver))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPassenger().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelRequest;
    private javax.swing.JToggleButton btnConnect;
    private javax.swing.JButton btnRequestDriver;
    private javax.swing.JLabel lbConnectionState;
    private javax.swing.JLabel lbDriversAvailable;
    private javax.swing.JLabel lbRequestState;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCancelRequest() {
        return btnCancelRequest;
    }

    public JButton getBtnRequestDriver() {
        return btnRequestDriver;
    }

    public JLabel getLbConnectionState() {
        return lbConnectionState;
    }

    public JLabel getLbDriversAvailable() {
        return lbDriversAvailable;
    }

    public JLabel getLbRequestState() {
        return lbRequestState;
    }

    public JToggleButton getBtnConnect() {
        return btnConnect;
    }

    
}
